#!/bin/ksh
#
# Description:
#   Test creating a neighbour-joining tree (scoredist distance correction)


RC=0

test_name=`basename $0`
test_dir=`dirname $0`
data_dir=$test_dir/../../../data
results_file="$test_dir/$test_name""_results"

# Run belvu and check if there are any differences to the saved results
diffs=`belvu -T nb -o tree  $data_dir/ALIGN.selex >&1 | diff "$results_file" -`

# If there were any problems or differences, set RC
if [[ $? -ne 0 || $diffs != "" ]]
then
  print "$test_name FAILED"
  RC=1
fi

exit $RC

