#!/bin/ksh
#
# Description:
#   Read in an alignment that has a separator of '='
#   between the sequence name and coords. Save the 
#   alignment without saving coords so that we know
#   the coords have been stripped from the name correctly
#   Also tests saving without coords in MSF format.


RC=0

test_name=`basename $0`
test_dir=`dirname $0`
data_dir=$test_dir/../../../data
results_file="$test_dir/$test_name""_results"

# Run belvu and check if there are any differences to the saved results
diffs=`belvu -z '=' -C -o MSF $data_dir/PF02171_seed_separator.stock >&1 | diff "$results_file" -`

# If there were any problems or differences, set RC
if [[ $? -ne 0 || $diffs != "" ]]
then
  print "$test_name FAILED"
  RC=1
fi

exit $RC

