#!/bin/ksh
#
# Description:
#   Test saving a file to MSF format

RC=0

test_name=`basename $0`
test_dir=`dirname $0`
data_dir=$test_dir/../../../data
results_file="$test_dir/$test_name""_results"

# Run belvu and check if there are any differences in output to the
diffs=`belvu -o MSF $data_dir/PF02171_seed.stock >&1 | diff "$results_file" -`

# If thre were any problems or differences, set RC
if [[ $? -ne 0 || $diffs != "" ]]
then 
  print "$test_name FAILED"
  RC=1
fi

exit $RC
