#!/bin/ksh
#
# Description:
#   Test loading of a saved dot-matrix.
#
# Results:
#   Dotter should start up in graphical mode. You should be able to interact
#   with the dot-plot as if it were created from the original sequences (test1).,
#   including being able to adjust the contrast using the greyramp tool.
#

RC=0

test_name=`basename $0`
test_dir=`dirname $0`
data_dir=$test_dir/../../../data

dotter -l $data_dir/chr4_vs_DA730641.dot -q 246634 -f $data_dir/chr4_dna_align.gff $data_dir/chr4_ref_seq_short.fasta $data_dir/DA730641.fasta

# If there was an error, set RC
if [ $? -ne 0 ] 
then
  RC=1
fi

exit $RC
