#!/bin/ksh
#
# Description:
#   Test Dotter in nucleotide->nucleotide mode, using the reverse-complemented version of the input
#   match sequence. Also tests starting up in HSP mode.
#
# Results:
#   Dotter starts up showing HSPs. Enable the pixelmap from the View menu to see if the alignments
#   in the calculated dot-plot match the positions of the HSPs. The pixelmap and the HSPs show 
#   matches from the (reverse-complemented) match sequence against both strands of the reference
#   sequence.
#

RC=0

test_name=`basename $0`
test_dir=`dirname $0`
data_dir=$test_dir/../../../data

dotter -q 246634 -v -H -f $data_dir/chr4_dna_align.gff $data_dir/chr4_ref_seq.fasta $data_dir/DA730641.fasta

# If there was an error, set RC
if [ $? -ne 0 ] 
then
  RC=1
fi

exit $RC
