
INSTALLING SEQTOOLS ON MAX OS X
===============================

Install the following pre-requisites. We strongly recommend that you use
MacPorts to install these packages as this will also install any dependencies
for you.

    curl    (optional)
    gtk2
    glib2
    sqlite3 (optional)
    gcc47   (or greater; see note below)

Note that you need a compiler that supports C++11, e.g. gcc version 4.7 or
greater. C++11 is required as of seqtools 4.41.0. If you have an older compiler,
you can still install seqtools version 4.40.0 and earlier.

In the terminal, unpack the downloaded seqtools tar file using the following
command, where XXX is the version you downloaded:

    tar -xf seqtools-XXX.tar.gz

To install in the default location (usually /opt/local/bin):

    cd seqtools-XXX
    ./configure 
    make 
    make install 


To install in a different location, or for help with dependencies or for more
detailed instructions on configure see the tips below and also the INSTALL file
in this directory.


Environment
-----------

Before running the programs, you need to set the DISPLAY environment variable to
tell GTK which screen to use. Typically you would set this to ":0" (without the
quotes) to mean the first display on the local machine.

To do this automatically every time you open a new terminal, you can add it to
your profile using the following command (this only needs to be done once and
will then affect all new terminals):

In bash:

  echo "export DISPLAY=:0" >> ~/.bash_profile

or in csh:

  echo "setenv DISPLAY :0" >> ~/.cshrc

You also need to have XQuartz or X11 running to run GTK programs on a Mac. One
or both of these may be installed by default on your machine. If not, you can
download XQuartz from here:

  https://www.xquartz.org/


Tips
----

You may need to run make install using sudo if you do not have root privileges,
i.e.:

    sudo make install

Alternatively, to install to a different location (e.g. one not requiring root
privileges), use the --prefix argument when you run ./configure. For example,
the following command would set the install location to foo/bar in your home
directory:

    ./configure --prefix=~/foo/bar

If GTK+ is not in the default location then you may need to pass its location to
the configure script. GTK+ is usually installed in /usr/lib, /usr/local/lib,
/opt/lib or /opt/local/lib. If GTK+ is in e.g. /opt/local/lib then you would
call configure with the following arguments:

    ./configure PKG_CONFIG_PATH=/opt/local/lib/pkgconfig LDFLAGS="-Xlinker -rpath -Xlinker /opt/local/lib"


